<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * filmRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FilmRepository extends EntityRepository
{
    public function paginate($offset){
        $qb = $this->createQueryBuilder("f");
        
        $query = $qb->setFirstResult($offset)
                    ->setMaxResults(4)
                    ->getQuery();
        
        $paginator = new Paginator($query);
        
        return $paginator;
    }
}
